spring.application.name=cellbank

spring.datasource.url=jdbc:postgresql://localhost:5432/cellbank
spring.datasource.username=cellbank_app
spring.datasource.password=${CELLBANK_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=never